### ISSUE TITLE
lockFileMaintenance clarification

### ISSUE THREAD

**Issue by charlike** [renovateapp/config-help#1]
Still cant get it right.

let say I will use yarn, pinVersions:true for all kinds of deps and some days passed of autoupdating and automerging. I think after every new update it should regenerate the lockfile, so when u clone the repo and run install u will get correct deps. is that option for that?

I seen today some new opened issue at renovate repo for smth like that, but how it differs from the lockfilemaintenance option?

**Comment by rarkins** [comment]
Every time a dependency is updated, Renovate will regenerate the lock file from scratch so you will have the very latest of both direct dependencies plus sub-dependencies. Hence, if you are updating dependencies frequently then your lock file will also be likely to be fairly up to date.

Note that Renovate won't keep updating lock files in a PR constantly - they will only be updated/regenerated if the `package.json` is updated by another dependency version.

If it has been a while since the last Renovate PR/lockfile then your dependencies may be "out of date" (if using semver ranges) plus also sub-dependencies can always get out of date quickly, if you care. That's where "lock file maintenance" can help, because it will also regenerate the lock file even if `package.json` hasn't been updated. By default lock file maintenance has a schedule of "before 5am on monday" so that it disturbs at most once per week. If you left it running continuously you'd probably end up with lock file updates every hour or two and not many people would really want that.

**Comment by charlike** [comment]
> they will only be updated/regenerated if the package.json is updated by another dependency version.

same as in the docs. I cant understand exactly that. what mean only if is updated by another, when it is touched/changed in every pr for new dep..

> If you left it running continuously you'd probably end up with lock file updates every hour or two and not many people would really want that.

why not? is the commit prefix `chore`?

**Comment by rarkins** [comment]
> same as in the docs. I cant understand exactly that. what mean only if is updated by another, when it is touched/changed in every pr for new dep..

lock files are regenerated only if `package.json` changes in a branch. e.g if PR is created to upgrade to prettier v1.7.1, and then soon after prettier v1.7.2 is released then the lock file will be updated too. But if v1.7.1 PR sits open for a week without you merging it then Renovate won't keep regenerating the lock file every hour "just in case" some sub-dependency has changed.

> why not?

People don't want disruptions/notifications too often. And very wasteful for the server running Renovate too, i.e. you'd need a VCPU per project or every few projects if you insist on regenerating every lock file non stop.

**Comment by charlike** [comment]
im fan of the "rolling release" model, and so probably thats why I keep evrything uptodate at maximum.. :d

anyway, I think Im starting to get it. and would be good to run regenerate when new update/pr is sent (probably for that is the mentioned seen issue in the other repo).

**Comment by charlike** [comment]
oh, I think I got it. alright, i'll keep it "on mondays" only, i's okey.
