### ISSUE TITLE
`semanticCommitType` has no effect?

### ISSUE THREAD

**Issue by emilio-martinez** [renovateapp/config-help#15]
When setting up Renovate I used the `semanticCommitType` config option as mentioned in the [config docs](https://renovateapp.com/docs/configuration-reference/configuration-options#semanticcommittype). However, it had no effect. `semanticCommitScope` did.

```js
{
  ...
  "semanticCommits": true,
  "semanticCommitType": "build",
  "semanticCommitScope": "package",
  ...
}
// => chore(package): ...
```

After some googling around, I found that `:semanticCommitTypeAll()` was mentioned on some Markdown file on the Renovate repo, so I tried it and it worked!

This issue is to document that the config shown above didn't, which is not clear to me why. For reference, this is the code change that I ended up using:

https://github.com/emilio-martinez/is-datatype/pull/82/commits/3c16db0569e5706a7d0546d3fe39e11d98e6c9ec

**Comment by rarkins** [comment]
The Renovate approach to config is “cascading”, but like CSS that also can have its downsides when things aren’t obvious. 

The problem you faced is that you need to override the semanticType at all levels where it’s set, not just the top level. The app itself has defaults and then you have accepted the “config:base” preset which contains even more opinionated settings, such as “fix” for dependencies and “chore” for devDependencies. 

Perhaps the best thing to do is to add a note to the docs for semanticType warning that you may need to override multiple locations if you use other presets plus manual config, or else use the preset you mentioned. My goal is that most config can be done with presets so that you avoid these types of problems (and the onboarding PR recommends that too, although it’s easy to overlook).

**Comment by emilio-martinez** [comment]
Yeah, I actually saw that note on the onboarding PR, but I think there were a couple thinks that threw me off the righteous path:

- I wasn't super clear on where to find valid values for `extends`. For example, [searching for `semanticCommitTypeAll` on the repo](https://github.com/renovateapp/renovate/search?utf8=%E2%9C%93&q=semanticCommitTypeAll&type=) returns some markdown files, but not actual definitions files, which initially made me think that those recommendations may not apply anymore.
- The onboarding docs mention ["Common Overrides" as properties](https://renovateapp.com/docs/getting-started/configure-renovate#common-overrides), which made me attempt to override on a property-per-property basis.

In any case, I'd be happy to help with documentation. Is there a part of the code I should be looking at to get a full list of the allowed values?

**Comment by rarkins** [comment]
Help with documentation would be greatly appreciated! Anything that helps future users will be the gift that keeps on giving. I've been using/writing it for so long that it's sometimes hard for me to notice when info is missing or misleading.

Within renovateapp/renovate:
- The ultimate reference file listing all options and their defaults is https://github.com/renovateapp/renovate/blob/master/lib/config/definitions.js
- The source code for https://renovateapp.com/docs/configuration-options is https://github.com/renovateapp/renovate/blob/master/website/docs/_posts/2017-10-05-configuration-options.md
- The source code for the Onboarding PR text is at https://github.com/renovateapp/renovate/blob/master/lib/workers/repository/onboarding/pr/index.js

The source code for all presets I publish is at https://github.com/renovateapp/renovate-config. "default" presets (those that have just a `:` prefix) are specifically here: https://github.com/renovateapp/renovate-config/tree/master/packages/renovate-config-default
