### ISSUE TITLE
Rebasing Stale and Scheduled Lockfile Maintenance PRs

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/config-help#16]
We use configuration that schedules a weekly lockfile maintenance pull request. We also have many projects that require a pull request be rebased against the latest commit in the `master` branch before they can be accepted.

However, it looks like our on-premise Renovate (version `11.36.2`) won't update an existing lockfile maintenance pull request until the next scheduled time. That lead to unmergable lockfile maintenance pull requests (technically we can manually rebase the pull request branch through GitHub's UI, but then developers have to sit around until CI status checks pass again. i'd really like to see the entire process automated)

Is there a way to instruct Renovate to rebase stale lockfile maintenance pull requests outside of the scheduled time?

**Comment by rarkins** [comment]
I added some fixes for rebasing lock file PRs today but need to set up a test for in/out of schedule to check if it satisfies this request already or not.

Same rebase logic should apply as with normal branches - by default it rebases only if conflicted. Otherwise if repo is configured with branch protection requiring PRs be up to date then we detect that too and rebase whenever master changes.
