### ISSUE TITLE
`timezone` is ignored

### ISSUE THREAD

**Issue by teppeis** [renovateapp/config-help#17]
https://github.com/teppeis/kintone-plugin-packer/pull/68
The above PR was created at 2018-03-15 9:45 AM Asia/Tokyo (2018-03-15 0:45 UTC).
But I specified `"schedule:daily"` (it means daily 0am-2am) and `"timezone": "Asia/Tokyo"` in [renovate.json](https://github.com/teppeis/kintone-plugin-packer/blob/e9d45805089875547b694436b4a4f62f495898a6/renovate.json) and renovate-bot recognized it and wrote in the PR summary:

> Note: This PR was created on a configured schedule ("before 2am" in timezone Asia/Tokyo) and will not receive updates outside those times.

The timezone setting seems to be ignored.
In UTC, the created time is 0:45am and it's before 2am.

**Comment by rarkins** [comment]
@teppeis thanks for raising this - I'll take a look

**Comment by rarkins** [comment]
Looking at the PR, we can see that the *commit* was made within the correct timezone/schedule:

![image](https://user-images.githubusercontent.com/6311784/37444044-07162f00-2810-11e8-922f-5da9bde7e3c9.png)

You also have the preset `:prNotPending`, which tells Renovate "do not raise the PR for a branch until all tests have passed, or at least one has failed", i.e. when it's green or red.

You also have the setting ":unpublishSafe" which says that Renovate itself should set a "pending" status on any npm releases that are < 24 hours old. So this would prevent PRs from being created within the first 24 hours.

The combination of these settings means:
1. Branches will be created within the 0-2am time in Tokyo
2. PRs will be raised for the branch once the 24 hour unpublish window has elapsed

This is all "expected" behaviour, but maybe it does not suit your preferences. If you set the config option `"updateNotScheduled": false` in your config then this will mean that Renovate won't do anything at all outside of schedule, e.g. it won't raise non-pending PRs or do any conflict fixing etc - it will strictly keep its actions to the schedule. In your case this would most likely mean that branches are created on day 1 and then PRs created on day 2 once they are no longer pending.

Because of your short window for schedule, you may want to remove the "prNotPending" setting so that the PR is raised immediately even while tests are still running.

**Comment by teppeis** [comment]
@rarkins Thank you for quick response!
I'll set `:noUnscheduledUpdates`.
