### ISSUE TITLE
How to split an existing monorepo PR

### ISSUE THREAD

**Issue by wKovacs64** [renovateapp/config-help#19]
Renovate grouped `react` (`dependency`) and `react-test-renderer` (`devDependency`) into "react monorepo" under a single PR. What if I want to separate them and only accept one? What's the recommended workflow at this point?

Thanks.

**Comment by rarkins** [comment]
You're seeing that because you're using the `config:base` preset, which includes the `group:monorepos` preset, which itself includes the `group:react-monorepo` preset. 

Unfortunately right now, presets are a kind of "all or nothing" thing - you cannot disable individual rules within it. I have this feature request open on the main Renovate repo to implement the ability selectively disable subrules: https://github.com/renovateapp/renovate/issues/841

Until then, the options for you I can think of are:

1. Stop using `config:base` and instead add in the individual rules you want. The list is here: https://github.com/renovateapp/renovate-config/blob/310a0ff000328afdc68e2381a193f0cdcd860898/packages/renovate-config-config/package.json#L18-L35

2. Write a packageRule to attempt to disable the bundled one

Here's the source for the bundled one:
```
    "reactMonorepo": {
      "packageRules": [
        {
          "description": "Group packages from react monorepo together",
          "extends": "monorepo:react",
          "groupName": "react monorepo"
        }
      ]
    },
```

So I *think* this should work if you add it to your config:

```
      "packageRules": [
        {
          "description": "Disable react monorepo grouping",
          "extends": "monorepo:react",
          "groupName": null
        }
      ]
```

The `description` field is optional but may help you and others remember why it's there

**Comment by wKovacs64** [comment]
Confirmed, option 2 worked as expected. Thanks!
