### ISSUE TITLE
github app installed, no onboarding PR received

### ISSUE THREAD

**Issue by dmose** [renovateapp/config-help#21]
I installed the renovate app to one of my own repos (dmose/activity-stream, which is a fork of mozilla/activity-stream) several hours ago, and have yet to receive an onboarding PR.  Should I wait longer, or is something not working?

**Comment by rarkins** [comment]
Renovate ignores forked repositories by default, so you will need to add a `renovate.json` config in order to override that. I suggest starting with:

```
{
  "extends": ["config:base"],
  "renovateFork": true
}
```

Let me know if you don't see activity within minutes after that. Typically forked repositories are checked only daily, however if we see a webhook from GitHub notifying that a `renovate.json` got added then we *should* process the repo immediately.

**Comment by rarkins** [comment]
@dmose please reopen if that didn't fix your problem

**Comment by dmose** [comment]
@rarkins OK, thanks so much for the tip!  So the reason I'm doing this on a fork is as a way to try it out before doing it on the more important copy of the repo.

I've just added renovate.json, and so far, it's sent a couple of dependency PRs, but not an onboarding PR, from what I can see.  

I quite like the release notes and commits sections in the github integration.  Thanks!

**Comment by rarkins** [comment]
Yes, there are no onboarding PRs for any repository that has a renovate.json
