### ISSUE TITLE
shared config + encrypted npm token = failure to update

### ISSUE THREAD

**Issue by ahmadnassri** [renovateapp/config-help#22]
First off, thank you for building renovate, I've been searching for exactly this level of configuration and simplicity in configuring a dependency management service! very happy to see the level of features you've built, including the shared config, which is key for big organisations with 700+ repos (such as ours)!!!

I'm facing a bit of trouble with the shared config and encrypted npm tokens:

###### `@orgname/renovate-config`: `package.json`

```json
"renovate-config": {
    "default": {
      "extends": [
        "config:js-app",
        "schedule:daily"
      ]
    },
    "lockFileMaintenance": {
      "enabled": true,
      "extends": "schedule:weekly"
    },
    "labels": [
      "dependencies"
    ],
    "prHourlyLimit": 0,
    "prConcurrentLimit": 0,
    "semanticCommits": true,
    "rebaseStalePrs": true,
    "ignoreNpmrcFile": true,
    "encrypted": {
      "npmToken": "[redacted]"
    }
  }
}
```

###### every repo's `renovate.json`

```json
{
  "extends": [
    "@orgname"
  ]
}
```
I get this error issue created:

```
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

File: path/package.json
Error type: Failed to look up npm dependency @orgname/package-name
Message: This dependency lookup failure will cause all lock file updates to fail. Please either remove the dependency, or remove the lock file, or add npm authentication, or set updateLockFiles to false in your config.
```

- am I doing something wrong?
- are encrypted npm tokens supported with shared configs?
- is there a way for users like me to get a better debugging info on these types of errors?
- how do I trigger renovate to run per repo if the changes are made in the shared config? (assuming the hourly limits configs are stored server side, I can't overwrite those when I make changes to config?)

**Comment by rarkins** [comment]
Hi, glad to hear you are liking the looks of Renovate.

> am I doing something wrong?

No, it looks like a good way to configure, and I intend to get it to work as-is unless there's something I'm missing.

> are encrypted npm tokens supported with shared configs?

It's possible they're not being decrypted properly. This would be my first guess as well. I will look into the logs tomorrow (I can guess which account you're referring to, based on my logs).

> is there a way for users like me to get a better debugging info on these types of errors?

Not right now directly (a web portal with direct access to debug-level logs is in planning). You couldn't replicate the decryption 

> how do I trigger renovate to run per repo if the changes are made in the shared config? 

Currently we don't have that level of webhook capability but it's a good idea.

> (assuming the hourly limits configs are stored server side, I can't overwrite those when I make changes to config?)

We add each onboarded repository to our job queue per hour, and each onboarding repository once per day. These are meant to "catch" any updates that we didn't become aware of due to webhooks. We trigger renovations whenever we receive relevant webhooks such as `package.json` updated, `renovate.json` updated, etc and there's no limits on this. So the best way to test would be to have a test repo you don't mind polluting `master` with and just keep updating `package.json` with something to trigger a new renovation.

**Comment by rarkins** [comment]
@ahmadnassri looks like there's an error in your preset, please see https://github.com/telusdigital/renovate-config/pull/1

**Comment by ahmadnassri** [comment]
> It's possible they're not being decrypted properly. This would be my first guess as well. I will look into the logs tomorrow (I can guess which account you're referring to, based on my logs).

Thank you, FYI: I used the following to generate and encrypt the token:

```bash
$ npm token create --read-only
$ echo "redacted" | npx renovate-encrypt
```

> Not right now directly (a web portal with direct access to debug-level logs is in planning). You couldn't replicate the decryption

a web portal would be immensely helpful to track schedules and onboarded repos in an org!

> Currently we don't have that level of webhook capability but it's a good idea.

:+1: 

> So the best way to test would be to have a test repo you don't mind polluting master with and just keep updating `package.json` with something to trigger a new renovation.

good to know, I'll try to muck around with that :+1:

**Comment by ahmadnassri** [comment]
we posted our comments at the same time! thank you for finding the issue! I'll keep testing!

**Comment by rarkins** [comment]
@ahmadnassri I triggered a manual renovation of one of your affected repositories and it no longer seems to have the auth error. However due to schedules, it may not be creating PRs just right now

**Comment by ahmadnassri** [comment]
@rarkins excellent, thank you! I'll wait it out and see how it works over time
