### ISSUE TITLE
Auto-merging Docker Updates

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/config-help#24]
How do I auto-merge the `sha` update for Docker pull requests in my `.circleci/config.yml` file?

Example - https://github.com/factset/labeledpipe/pull/56/files

**Comment by destroyerofbuilds** [comment]
Thank you @rarkins! I just updated my `renovate.json` file, and I'll let you know how it goes.

On a related note, it seems I already had [`automerge`](https://github.com/factset/labeledpipe/blob/bd0a3b0969eeb71f7afe5a252aa3df02274a9a08/renovate.json#L3) globally enabled, and only disabled for `major` changes.

Does `automerge` at the top level not get applied to `digest`?

**Comment by rarkins** [comment]
@destroyerofbuilds in that case it should logically have been automerged. I'll check the logs for why and fix if it turns out to be a bug

**Comment by rarkins** [comment]
@destroyerofbuilds I checked the logs and found "GitHub blocking PR merge" which indicates that GitHub returned a 405 error when we attempted to merge: 
https://github.com/renovateapp/renovate/blob/b6cf7360e2325d6d8264115082cce85923b69732/lib/platform/github/index.js#L1004-L1006

Strange thing is that I don't see any log that we prior *detected* branch protection, so I have improved the debug a little and will see what it says soon.

**Comment by rarkins** [comment]
The GitHub 405 returns "Base branch requires signed commits. Rebase merges cannot be automatically signed by GitHub"

At least we have an answer, however it's confusing to me. Renovate's commits *are* signed, e.g. here is the one from that branch: https://github.com/factset/labeledpipe/pull/62/commits/897a1a558d53c3ab2fee7288d787b64b305e7cb9

And when I merge Renovate PRs manually through the GitHub UI using rebase merge, I do so precisely because the commits will remain as Verified once they are rebased onto `master`. However I have only tried it using repositories that don't have signed commits *enforced*.

It seems that the API accepts a merge *squash* though, so I have updated Renovate's automerge logic so that if it fails with a 405 for rebase automerging then it keeps trying and will try squash after rebase. You can see that it worked with https://github.com/factset/labeledpipe/pull/62

**Comment by destroyerofbuilds** [comment]
> Renovate's commits are signed

Which is why I felt confident enabling enforcement of signed commits. 

I'm sorry for the trouble that setup caused you. Thank you for working through the issue, and for our benefit in having fully automated digest updates.
