### ISSUE TITLE
Is `supportPolicy: lts_latest` what I think?

### ISSUE THREAD

**Issue by olstenlarck** [renovateapp/config-help#28]
Heya!

I have some thoughts for long future release cycle... And if i'm not the maintainer of my org and my packages anymore, or something happened to me or such things.. 

If i configure Renovate to `supportPolicy: lts_latest`, is it meaning that when Node v10 goes LTS in October 2018 it will change from latest 8 version to v10 lts versions?

I just want to ensure that all my packages will always require _last_ lts. And more specifically, which isn't currently possible i believe, that: at least v8.9 (first v8 LTS release), currently. And when v10 lands in LTS to switch to that version, say v10.9 for example. Because i don't exactly want to force people to always be on the latest patch or minor version to use my package - that's the reason i didn't "pin" the engines field to allow that feature to work.

**Comment by rarkins** [comment]
Right now, `supportPolicy` is only used for `travis`, because it's the only node version manager we support that has the possibility of multiple versions.

It's my goal though that `supportPolicy` would be configured in the `node` object and apply consistently to all package managers that include Node.js. So that means yes - updating from v8 to v10 in October.

I think it would be beneficial to allow users to either:
(a) Require the minimum *LTS version*, e.g. v8.9 or v10.9 e.g. `>= 8.9`
(b) To require the minimum *secure* version, e.g. the Node.js project currently recommends v8.11.0 so it would be `>= 8.11.0`

**Comment by rarkins** [comment]
Maybe if you want to request any enhancements to support this, you can raise a feature request in the main repo to track it that way.
