### ISSUE TITLE
Private node modules – Onboarding PR

### ISSUE THREAD

**Issue by allybee** [renovateapp/config-help#3]
Your [documentation](https://renovateapp.com/docs/getting-started/configure-renovate#no-risk-onboarding) states:
> Renovate will keep updating the description in the PR to match

I enabled Renovate for my repo containing privately hosted node modules. I received the onboarding PR with dependency lookup warnings, so I created a token using `renovate-encrypt` and updated my `renovate.json` to the following:

```json
{
  "extends": [
    "config:base"
  ],
  "labels": [
    "chore",
    "bot"
  ],
  "encrypted": {
    "npmToken": "[redacted]"
  }
}
```

All of the dependency lookup warnings still exist in the PR, saying:
> `[dependency]`: Failed to look up dependency. This will block all dependencies from being updated due to presence of lock file.

How can I troubleshoot Renovate's authentication with the encrypted npmToken?

**Comment by rarkins** [comment]
Hi @allybee, thanks for your question. Logging for tokens and encryption is a little sparse, partly because I want to reduce the risk of ever leaking them. I will look for the repository you describe and take a look at the logs I have on server side (which also don't log any decrypted data, but it should still help).

**Comment by rarkins** [comment]
I think the problem might be that there is also an `.npmrc` file committed in the repository as well. When we decrypt an `npmToken`, we actually convert it to an `.npmrc` string like this:
```
if (eKey === 'npmToken') {
    logger.info('Migrating npmToken to npmrc');
    decryptedConfig.npmrc = `//registry.npmjs.org/:_authToken=${decryptedStr}\n`;
}
```

In your case, this might even cause two problems.

(1) It looks like you are using a custom registry, but we set it for the public npmjs registry as you can see above
(2) It's possible that we are overwriting this configured/encrypted string with the file we get in the repository (I need to confirm that)

Assuming you do not commit an npm token line in the .npmrc in the repository, one way we could approach this is:
- Configure Renovate to ignore the .npmrc in the repository, and
- You encrypt a whole .npmrc including registry *and* auth information and put that in your config instead of the current npmToken

**Comment by rarkins** [comment]
@allybee have you made any changes to your config today? I think you should be ok to leave it as it was (i.e. encrypted npmToken) and I will try to adjust Renovate's behaviour to suit. Please confirm if it's still correctly configured.

**Comment by allybee** [comment]
@rarkins Thank you so much for investigating! I have not made any changes.

**Comment by rarkins** [comment]
@allybee I've tried a few things on the server side. The last thing left to check is.. is the token correct? To be sure, could you regenerate it and update the `renovate.json`?

e.g. generate:
```
echo "a-token-you-know-works" | renovate-encrypt
```

..and then put that encrypted string into our config as you had before. The one you have there decrypts OK, but it is being rejected by your private npm host.

**Comment by rarkins** [comment]
@allybee FYI, there's a new error on your project since last night - all lookups fail with "CERT_HAS_EXPIRED". Looks like your custom registry certificate has expired.
