### ISSUE TITLE
Is it possible to override the semanticPrefix?

### ISSUE THREAD

**Issue by wopian** [renovateapp/config-help#6]
`fix(deps)` is used for `dependencies` from the discussion in https://github.com/renovateapp/renovate/issues/303, which I personally don't agree with, since an update should only be considered a `fix` if the default branch is current failing and upgrading this package *fixes* it imo.

Recently [attempted](https://github.com/wopian/hibari/commit/d06c68cdbe76da47d8c0ada457eae7f866f918b7) to suppress these `fix(deps)` in PRs/commits in my repos by replacing `{{semanticPrefix}`.

```diff
- "commitMessage": "{{semanticPrefix}}update {{depName}} to {{newVersion}}"
+ "commitMessage": "chore(deps): update {{depName}} to {{newVersion}}"
```

However the default semantic prefixes are still added (with `semanticCommits: false` also set), creating this wonderful PR title 😆 

![](https://i.imgur.com/moyf3Az.png)

**Comment by rarkins** [comment]
Instead of editing templates directly, try adding `”:semanticPrefixChore”` to your `extends` array

**Comment by rarkins** [comment]
BTW it’s classified as a fix only in order to bump the version according to semantic release, because if you change a production dependency then it’s a good idea to increment a patch.

**Comment by rarkins** [comment]
One more explanation: the `{{semanticPrefix}}` string is no longer used/needed in templates as it is added implicitly in the code. If you dig deep into Renovate’s code you can see that we actually strip this string from the start of user templates if we find them (ie like in your config). So when you removed the string, it ultimately didn’t change anything.

I plan to one day add a feature to raise a “config migration” PR for anyone whose config uses old terminology so you can migrate in one click by merging they PR. I’ve held off on that because I want to manually review enough of them first to make sure they’re correct.

I think I will also add a new documentation page too, to unify these semantic commit message settings.

**Comment by wopian** [comment]
>One more explanation: the {{semanticPrefix}} string is no longer used/needed in templates as it is added implicitly in the code.

Yeah, I made my config around when you launched. Gone though the docs and updated everything to use the `extends` plugin feature 👍

Thanks for the help and notice of the deprecations @rarkins 😃

**Comment by wopian** [comment]
Using `:semanticPrefixChore` still contains `fix(deps)` commits with the [following config](https://github.com/wopian/tracker-killer/blob/bb6c464d3de78292668437d5b5c66e75fd07ca66/package.json#L46): 

```json
"renovate": {
  "extends": [
    ":npm",
    ":preserveSemverRanges",
    ":combinePatchMinorReleases",
    ":renovatePrefix",
    ":semanticCommits",
    ":semanticPrefixChore",
    ":rebaseStalePrs",
    ":unpublishSafe",
    ":prNotPending",
    ":automergeDisabled",
    ":maintainLockFilesMonthly",
    ":ignoreUnstable",
    ":updateNotScheduled",
    ":label(dependencies)",
    ":timezone(Europe/London)",
    ":assignee(wopian)",
    "group:babelMonorepo"
  ],
  "prTitle": "update {{depName}} to {{newVersion}}",
  "commitMessage": "update {{depName}} to {{newVersion}}"
}
```

![](https://i.imgur.com/YFjR2s0.png)

**Comment by rarkins** [comment]
Sorry, I told you the wrong preset the last time. If you replace ":semanticPrefixChore" with ":semanticCommitTypeAll(chore)" then it should work. Verified here: https://github.com/renovate-tests/tracker-killer

**Comment by wopian** [comment]
Thanks again 👌
